### PR TITLE
First draft of fixes #111, fixes #118

### LINKED ISSUE #111: BigDecimal narrowing
It would be nice if BigDecimal implemented the (currently internal) interface in BigNumber of NarrowingOperations<BigDecimal> to support changing BigDecimals back to all the various basic types; Int, Long, Short, Float, Double, UInt, UShort, ULong, Byte and UByte,

Since BigDecimal is not "open"  extension functions are required to do this.  An example of one is below. 
```
/**
 * Returns a long value that truncates any digits to the right of the decimal.
 *
 * @param exactRequired if true and non-zero truncation error would result
 * @throws ArithmeticException if the value is to large or too small for a long, or if
 * exactRequired true and value to right of decimal is non-zero
 */
fun BigDecimal.longValue(exactRequired: Boolean = false): Long {
    val limit = BigDecimal.fromLong(Long.MAX_VALUE)
    val lowLimit = BigDecimal.fromLong(Long.MIN_VALUE)
    if (this > limit || this < lowLimit)
        throw ArithmeticException("Narrowing to Long would lose significant digits")
    return checkTruncation(exactRequired)
}

private fun BigDecimal.checkTruncation(exactRequired: Boolean):Long {
    val result = this.divideAndRemainder(BigDecimal.ONE)
    if (exactRequired && !result.second.isZero()) {
        throw ArithmeticException("Narrowing would lose precision")
    }
    val work = this.minus(result.first)
    return work.significand.longValue(exactRequired)
}
```
This would provide a superset of the narrowing operations provided in java's BigDecimal

### LINKED ISSUE #118: Rounding issue on division
Given this code:
```
val dub = BigDecimal.fromDouble(Double.MIN_VALUE)
val dub2 = dub.divide(BigDecimal.TEN)
```
Infinite precision should be in use, so this should get 4.9E-325 for dub2. Initially the correct new exponent of -325 is calculated, but then in fun roundDiscarded stuff gets lost, resulting in this debug output:
```
dub = {BigDecimal@1887} "4.9E-324"
 precision = 2
 significand = {BigInteger@2118} "49"
  magnitude = {long[1]@2120} 
   0 = 49
  numberOfWords = 1
  stringRepresentation = null
  sign = {Sign@1924} "POSITIVE"
 exponent = -324
 decimalMode = null
dub2 = {BigDecimal@2115} "0.E-318"
 precision = 0
 significand = {BigInteger@2121} "0"
  magnitude = {long[1]@2124} 
   0 = 0
  numberOfWords = 1
  stringRepresentation = null
  sign = {Sign@2125} "ZERO"
 exponent = -318
 decimalMode = {DecimalMode@1896} "DecimalMode(decimalPrecision=0, roundingMode=NONE)"
```

### PR DESCRIPTION
**Pull request by skolson**
Narrowing functions that resolves #111 are mostly working. Fix #118 involved not using a roundDiscarded function when using unlimited precision. Also did some minor cleanup of Lint warnings in BigDecimal. Still needs comments, and some changes to BigInteger to allow unit tests to work in certain cases, and probably other stuff.

### CODE REVIEW

**Comment by skolson** [comment]
Hmm, my attempt at linking this pull to the two issues doesn't seem to work

**Comment by ionspin** [comment]
Try adding the # in front of the number of issue but in the description. Also if you say `fixes #issuenumber` or `closes #issuenumber` merging the pull request will automatically close those issues. Theres a list of of other words that are recognized here https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue

**Comment by ionspin** [comment]
I merged the fix for BigInteger long/ulong conversion into master, if you could update your branch with the latest master, hopefully the build will succeed. Also I hope I didn't make any other mistakes in that last pull request, it was rushed a bit.

File: bignum/src/commonMain/kotlin/com/ionspin/kotlin/bignum/decimal/BigDecimal.kt [hunk 1]
```diff
@@ -1231,6 +1261,97 @@ class BigDecimal private constructor(
...
+     * The next group of functions are implementations of the NarrowingOperations interface
+     */
+    /**
+     * Convert the current value to  Int.
+     * @param exactRequired True causes an ArithmeticException to be thrown if there is any loss of
+     * precision during the conversion, either side of the decimal. False truncates any precision to
+     * the right of the decimal.
+     */
+    override fun intValue(exactRequired: Boolean): Int {
+        return significand.intValue(exactRequired)
```
Comment (ionspin) [inline bignum/src/commonMain/kotlin/com/ionspin/kotlin/bignum/decimal/BigDecimal.kt:1274]: This won't be correct because it doesn't consider the exponent. Currently the BigDecimal is constructed like this:
`significand * exponent`. 
For example, if significand is 987654321 and exponent is 5, then resulting big decimal will be 9.87654321 * 10^5 = 987654.321

Each BigDecimal has also a precision member, which is just the number of digits in significand


You can see the current state if you run this code snippet:
```        
        val bigDecimal = BigDecimal.fromLongWithExponent(987654321, 5)
        println("Value: ${bigDecimal.toStringExpanded()}")
        val longValue = bigDecimal.longValue()
        println("Long value $longValue")
```

I think you can reuse the `BigDecimal.toBigInteger()`  because this will return a BigInteger that already has truncated the non-integer part or multiplied by a certain power and then we can narrow that BigInteger to long/int or whatever was requested. 

We would also need to check if the number that we are returning is exact as the original when `exactRequired=true`, as 123.4 will be returned as 123. You might check that by calling `.floor()` on the bigDecimal and checking if it's zero or not. Or there might be a more efficient way, I'm not completely sure about that part.

Comment (skolson) [reply bignum/src/commonMain/kotlin/com/ionspin/kotlin/bignum/decimal/BigDecimal.kt:1274]: Cool, fixing now. Also if it's OK I'd like to add these changes to the BigInteger narrowing functions using the unsigned types.  If I change this in longValue as an example:
```
   if (exactRequired && (this > Long.MAX_VALUE.toULong())) {
```
to this, it fixes an issue when this is negative:
```
        if (exactRequired && (this.abs() > Long.MAX_VALUE.toULong())) {
```

Comment (skolson) [reply bignum/src/commonMain/kotlin/com/ionspin/kotlin/bignum/decimal/BigDecimal.kt:1274]: Oops I think I clicked on the wrong thing and caused another build.  Anyway I think build failed cuz of my new tests failing. I'm gonna commit changes to address the issue above, and it also makes small changes to BigInteger.  In my environment the tests pass now. So won't be long and I'll post again, as soon as I figure out how to update a pull with a new commit :-)

Comment (skolson) [reply bignum/src/commonMain/kotlin/com/ionspin/kotlin/bignum/decimal/BigDecimal.kt:1274]: Question - on the unsigned narrows it needs to check for negative numbers and bail on those when exactRequired is true.  As part of making that change to both BigDecimal and BigInteger, would it be ok to add these two properties to the BigNumber interface? The java equivalents are handy...

```
    val isNegative get() = signum() < 0
    val isPositive get() = signum() > 0
```

Comment (skolson) [reply bignum/src/commonMain/kotlin/com/ionspin/kotlin/bignum/decimal/BigDecimal.kt:1274]: Let me know if that's ok, and I'll do a commit to the pull that hopefully gets the tests working again

Comment (ionspin) [reply bignum/src/commonMain/kotlin/com/ionspin/kotlin/bignum/decimal/BigDecimal.kt:1274]: > Also if it's OK I'd like to add these changes to the BigInteger narrowing functions using the unsigned types

Absolutely fine with adding that here, but I'm not sure if we can use abs(), because absolute value of BigInteger with value of Long.MIN_VALUE is 9223372036854775808 and we are comparing against Long.MAX_VALUE, which is one less at 9223372036854775807, so it would fail in that one case. I think we need to compare against both MIN_VALUE and MAX_VALUE

> Question - on the unsigned narrows it needs to check for negative numbers and bail on those when exactRequired is true. 

Once again, you are completely right we need that check if the BigInt is negative if exact is required, I'd just suggest either reusing the existing `sign` member of BigInteger (it's an enum with POSITIVE, NEGATIVE, ZERO value) or add the helpers as (there we save one call to signum() which does the same thing)
```
   val isNegative get() = sign == Sign.NEGATIVE
   val isPositive get() = sign == Sign.POSITIVE
```
And don't worry about restarting the builds, Travis CI offers them for free for open source projects, and the build for this library is not that long in any case.

Comment (skolson) [reply bignum/src/commonMain/kotlin/com/ionspin/kotlin/bignum/decimal/BigDecimal.kt:1274]: Ok, I got rid of the UInt usage in byteValue, shortValue, intValue and longValue, and inserted range checks. Gonna do a commit and figure out how to get the pull request updated.

Comment (ionspin) [reply bignum/src/commonMain/kotlin/com/ionspin/kotlin/bignum/decimal/BigDecimal.kt:1274]: Awesome! The pull request will update automatically when you push to your original branch, and it should also run the Travis build on the latest commit at the same time

**Comment by skolson** [comment]
Ok, my latest commit seems to be up there, hopefully this represents progress :-). I guess we wait to be sure the tests all work on the currently running CI build. Let me know if you see other things I need to change.

**Comment by skolson** [comment]
Oh, and just an FYI - the doubleValue and floatValue implementations are based on the same code in java's BigDecimal source for the same function. If you look you'll see the big similarity :-)

**Comment by ionspin** [comment]
I see the test are failing but just on JS platform, I'll have a look at it tomorrow, it's getting late here, JS target is usually more finicky than native and JVM and requires some weird workarounds. The important thing is that all JVM tests are passing.

**Comment by skolson** [comment]
Ok cool. I have NO experience with the JS stuff, so I'm no help there unfortunately :-)

**Comment by ionspin** [comment]
I found what the issue was, in JS Double.MIN_VALUE is Number.MIN_VALUE which is `5e-314`, and the parser implementation always expected a `.` in scientific notation. Pull request #121 should fix that, and when it's merged to master you can update this pull request and JS and the rest of the tests should pass.

Another note, I noticed your pull request also failed because of Spotless errors, spotless is a plugin that enforces code style rules, you can easily apply all the changes by running `gradlew.bat spotlessApply` or `./gradlew spotlessApply` and then committing whatever changes spotless made. Although sometimes Spotless can't apply the changes itself, but it will give you a list of what needs to be fixed.

**Comment by skolson** [comment]
Thanks, I'll go check out spotless

**Comment by skolson** [comment]
The spotless tweaks (not many) are committed

**Comment by skolson** [comment]
Ok, I think I got all the stuff done, will see what build does.

**Comment by ionspin** [comment]
Build and tests passed! Thanks for the contribution and all the issues reported, it really helps a lot!
